### ISSUE TITLE
Optimization Run

### ISSUE THREAD

**Issue by ghost** [AxelSemrau/ChronosMockPlugin#1]
I would like to expose Optimization Run in the SDK.
We can already run schedules, but it would be beneficial to automate or enforce running a optiization run from some scheduling plugins.

**Comment by PatrickKursawe** [comment]
1. How do you want to specify the method + column values? By referring to a sample list line or do you have to handle it seperate from the sample list?
2. How do you want to handle problems, like existing schedules that have to be removed? Just let chronos show the usual messages and be notified of the problem suffices?

**Comment by ghost** [comment]
I would handle it much like the run sample list. It should use line 1 of the existing sample list or loaded sample list. If there are problems have it return an error message. Or  if it is a bool have a error message to check.
if (!RunOptimization())
     Throw new exception(errorMessage);

Or
String samplelist="mysamplelist.csl";
if (!RunOptimization(samplelist))
      Throw new exception(errorMessage);

Steven W. Stiller, Ph.D.
Director of Analytical Technology
LEAP Technologies
(720) 663-7247tel:(720)%20663-7247

**Comment by PatrickKursawe** [comment]
Implemented in 4.5.0. You can just start the schedule. The event args have a new parameter for telling Chronos this is an optimization run. The used method will be overwritten after the optimization run without further questions.
